import { Claim } from '@/interfaces/claims';

export const claimsList: Claim[] = [{
  id: '1',
  details: {
    first_name: 'John',
    last_name: 'Doe',
    state: 'CA',
    is_not_cosmetic_claim: true,
    insurance_type: 'Health',
    insurance_provider: 'Blue Cross',
    date_of_claim_denial: '2023-04-15',
    claim_amount: '$5000',
    reason_for_claim_denial: 'Insufficient documentation',
    oon_emergency_service: 'Yes',
    oon_is_in_network_service: 'No',
    oon_is_signed_consent: 'Yes',
    consent_opt1: true,
    consent_opt2: false,
    consent_opt3: true,
    consent_opt4: false,
  },
  metadata: {
    createdAt: new Date().toISOString(),
    status: 'draft',
    updatedAt: new Date().toISOString(),
    updatedBy: 'Sridhar Madala',
  },
}];
//   ,
//   {
//     "id": "2",
//     "first_name": "Jane",
//     "last_name": "Smith",
//     "state": "NY",
//     "is_not_cosmetic_claim": false,
//     "insurance_type": "Dental",
//     "insurance_provider": "Delta Dental",
//     "date_of_claim_denial": "2023-05-20",
//     "claim_amount": "$2000",
//     "reason_for_claim_denial": "Non-covered service",
//     "oon_emergency_service": "No",
//     "oon_is_in_network_service": "Yes",
//     "oon_is_signed_consent": "No",
//     "consent_opt1": false,
//     "consent_opt2": true,
//     "consent_opt3": false,
//     "consent_opt4": true
//   },
//   {
//     "id": "3",
//     "first_name": "Alice",
//     "last_name": "Johnson",
//     "state": "TX",
//     "is_not_cosmetic_claim": true,
//     "insurance_type": "Vision",
//     "insurance_provider": "VSP",
//     "date_of_claim_denial": "2023-06-10",
//     "claim_amount": "$1500",
//     "reason_for_claim_denial": "Out of network",
//     "oon_emergency_service": "Yes",
//     "oon_is_in_network_service": "No",
//     "oon_is_signed_consent": "Yes",
//     "consent_opt1": true,
//     "consent_opt2": true,
//     "consent_opt3": false,
//     "consent_opt4": false
//   },
//   {
//     "id": "4",
//     "first_name": "Bob",
//     "last_name": "Williams",
//     "state": "FL",
//     "is_not_cosmetic_claim": false,
//     "insurance_type": "Auto",
//     "insurance_provider": "Geico",
//     "date_of_claim_denial": "2023-03-30",
//     "claim_amount": "$8000",
//     "reason_for_claim_denial": "Late submission",
//     "oon_emergency_service": "No",
//     "oon_is_in_network_service": "Yes",
//     "oon_is_signed_consent": "No",
//     "consent_opt1": false,
//     "consent_opt2": false,
//     "consent_opt3": true,
//     "consent_opt4": true
//   },
//   {
//     "id": "5",
//     "first_name": "Charlie",
//     "last_name": "Brown",
//     "state": "IL",
//     "is_not_cosmetic_claim": true,
//     "insurance_type": "Health",
//     "insurance_provider": "Aetna",
//     "date_of_claim_denial": "2023-07-22",
//     "claim_amount": "$3000",
//     "reason_for_claim_denial": "Pre-existing condition",
//     "oon_emergency_service": "Yes",
//     "oon_is_in_network_service": "No",
//     "oon_is_signed_consent": "Yes",
//     "consent_opt1": true,
//     "consent_opt2": false,
//     "consent_opt3": true,
//     "consent_opt4": false
//   },
//   {
//     "id": "6",
//     "first_name": "Diana",
//     "last_name": "Prince",
//     "state": "WA",
//     "is_not_cosmetic_claim": false,
//     "insurance_type": "Home",
//     "insurance_provider": "State Farm",
//     "date_of_claim_denial": "2023-02-18",
//     "claim_amount": "$6000",
//     "reason_for_claim_denial": "Non-covered peril",
//     "oon_emergency_service": "No",
//     "oon_is_in_network_service": "Yes",
//     "oon_is_signed_consent": "No",
//     "consent_opt1": false,
//     "consent_opt2": true,
//     "consent_opt3": false,
//     "consent_opt4": true
//   },
//   {
//     "id": "7",
//     "first_name": "Eve",
//     "last_name": "Miller",
//     "state": "OH",
//     "is_not_cosmetic_claim": true,
//     "insurance_type": "Health",
//     "insurance_provider": "Cigna",
//     "date_of_claim_denial": "2023-01-10",
//     "claim_amount": "$4000",
//     "reason_for_claim_denial": "Lack of prior authorization",
//     "oon_emergency_service": "Yes",
//     "oon_is_in_network_service": "No",
//     "oon_is_signed_consent": "Yes",
//     "consent_opt1": true,
//     "consent_opt2": true,
//     "consent_opt3": false,
//     "consent_opt4": false
//   }
// ]
